baseurl = "https://leguide-eap.netlify.app/"
title= "Le Guide de la formation présentielle, par l’EAP"
Paginate = 5

[params]
  env = "production"

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  chapters = "/:filename"

# datocms:start
title = "Le Guide de la formation présentielle, par l’EAP "
languageCode = "en"
# datocms:end
