baseurl = "https://eager-brahmagupta-48ef14.netlify.com"
title= "Le petit manuel de la formation présentielle par l'EAP"
Paginate = 5

[params]
  env = "production"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

# datocms:start
title = "Le petit manuel de la formation présentielle par l'EAP "
languageCode = "en"
# datocms:end
