baseurl = "/"
title= "Le Guide de la formation présentielle, par l’EAP"
Paginate = 5

[params]
  env = "development"

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  chapters = "/:filename"

# datocms:start
title = "Le petit manuel de la formation présentielle par l'EAP "
languageCode = "en"
# datocms:end
