baseurl = "https://eager-brahmagupta-48ef14.netlify.com"
title= "Le Guide de la formation présentielle, par l’EAP"
Paginate = 5

[params]
  env = "production"

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  chapters = "/:filename"

# datocms:start
title = "Le Guide de la formation présentielle, par l’EAP"
languageCode = "en"
# datocms:end
